module.exports=[
"Charles Bukowski",
"Joseph Goebbels",
"Winston Churchill",
"Lao-Tse",
"Confucio",
"Jesucristo",
"Joseph Stalin",
"Vladimir Putin",
"George W. Bush",
"Dwight Eisenhower",
"Osho",
"Nietzsche",
"Schopenhauer",
"Albert Einstein",
"Obama",
"Louis Pasteur",
"Napoleón Bonaparte",
"Adolf Hitler",
"Mahatma Gandhi",
"Juan Pablo II",
"Henry Ford",
"Steve Jobs",
"Bill Gates",
"Bill Murray",
"Yasser Arafat",
"Fidel Castro",
"El Ché Guevara",
"Jean Paul Sartre",
"Homero (el griego!)",
"Virgilio",
"Walt Disney",
"Lenin",
"Marx",
"Sócrates",
"Aristóteles",
"Platón",
"Octavio Paz",
"Isaac Newton",
"Buda",
"Elvis Presley",
"Edward Snowden",
"Benjamin Franklin",
"Michael Jackson",
"Oscar Wilde",
"George Washington",
"Euclides",
"Robert Oppenheimer",
"Ronald Reagan",
"Nikita Kruschev",
"Angela Merkel",
"Ban Ki-moon",
"Arnold Schwartzeneger",
"Charlie Sheen",
"Abraham Linclon",
"Nikola Tesla",
"Hugo Chávez",
"Mahoma (Muhammed)",
"Apóstol San Pablo",
"Keith Richards",
"John Lennon",
"Mike Jagger",
"J.R.R. Tolkien",
"George Orwell",
"Philip K. Dick",
"Carl Sagan",
"Steven Spielberg",
"Calígula",
"Julio Verne",
"Victor Hugo",
"Charles Baudelaire",
"Alexander Solzhenitsyn",
"Wolfgang Amadeus Mozart",
"Ludwig van Beethoven",
"Muhammad Ali",
"Salvador Dalí",
"Pablo Picasso",
"Vincent van Gogh",
"Neil Armstrong",
"Frida Kahlo",
"Diego Rivera",
"Antonio Vivaldi",
"J. S. Bach",
"Leo Tolstoi",
"Franz Kafka",
"Fyodor Dostoyevsky",
"Woody Allen",
"Stan Lee",
"Jorge Luis Borges",
"Charles Darwin",
"Genghis Khan",
"Paulo Coelho",
"Umberto Eco",
"George R. Martin",
"Mike Myers ",
"Tom Cruise",
"Andy Warhol",
"Kurt Cobain",
"Jim Morrison",
"Kim Jong-il",
"George Lucas",
"Claude Monet",
"John F. Kennedy",
"Pablo Neruda",
"Constantino",
"Alejandro Magno",
"James Joyce",
"Hermann Hesse",
"Quentin Tarantino",
"Anthony Hopkins",
"Lady Gaga",
"Ernest Hemingway",
"Brad Pitt",
"Cristiano Ronaldo",
"David Beckham",
"Madre Teresa de Calcuta",
"Jackie Chan",
"Jet Li",
"Sylvester Stallone",
"Angelina Jolie",
"Charlize Theron",
"Benicio del Toro",
"Mel Gibson",
"J. J. Abrams",
"Michael Bay",
"Julian Casablancas",
"David Bowie",
"Pierce Brosnan",
"Axel Rose",
"John Cena",
"J. K. Rowling",
"Lana Wachowski",
"Miguel de Cervantes",
"Edward Norton",
"Bruce Willis",
"Alex Turner",
"Marilyn Monroe",
"Beyoncé",
"Kanye West",
"Bill Clinton",
"Jim Carrey",
"Bob Dylan",
"Justin Bieber",
"Lindsay Lohan",
"Elton John",
"Greg Louganis",
"Richard Gere",
"Al Pacino",
"Robert Downey Jr.",
"Robert de Niro"]